name: Build
on:
  push:
    branches:
      - main # or the name of your main branch

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker build
        working-directory: ./DLLS.Comcer
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        
      - name: Publish
        working-directory: ./DLLS.Comcer
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
          
